spring:
  application:
    name: globalpay

  datasource:
    url: jdbc:postgresql://localhost:5432/globalpay
    username: devuser
    password: devpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true


  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    root: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

