app:
  scheduling:
    enabled: true
  gateway:
    url: ${GATEWAY_URL:https://globalpayments.com}
spring:
  application:
    name: globalpay

  datasource:
    url: jdbc:postgresql://localhost:5432/globalpay
    username: devuser
    password: devpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true


  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    root: INFO
    org.example.global_pay: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{requestId}] - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health, info,metrics, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      paymentGatewayCB:
        base-config: default
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
