spring:
  application:
    name: globalpay

  datasource:
    # Адрес твоего контейнера из docker-compose
    url: jdbc:postgresql://localhost:5432/globalpay
    username: devuser
    password: devpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true # Будем видеть в консоли все запросы к базе
    hibernate:
      ddl-auto: validate # Мы не даем Hibernate менять таблицы, это сделает Flyway
    properties:
      hibernate:
        format_sql: true

  # Настройки Flyway для миграций
  flyway:
    enabled: true
    baseline-on-migrate: true
